// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DataAsset {
    /**
     * Creates a new DataAsset instance.
     * @param {Partial<DataAsset>} [$$source = {}] - The source object to create the DataAsset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {DataAssetKind}
             */
            this["kind"] = DataAssetKind.$zero;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_url"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DataAssetStatus}
             */
            this["status"] = DataAssetStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cache_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content_sha256"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["size_bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_checked_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_updated_at"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataAsset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataAsset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataAsset(/** @type {Partial<DataAsset>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const DataAssetKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DataAssetKindRuleSet: "rule_set",
    DataAssetKindGeoSite: "geo_site",
    DataAssetKindGeoIP: "geo_ip",
    DataAssetKindSRSC: "srsc",
};

/**
 * @readonly
 * @enum {string}
 */
export const DataAssetStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DataAssetStatusPending: "pending",
    DataAssetStatusAvailable: "available",
    DataAssetStatusFailed: "failed",
};

/**
 * @readonly
 * @enum {string}
 */
export const DiagnosticSeverity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SeverityError: "error",
    SeverityWarning: "warning",
    SeverityInfo: "info",
};

export class Diagnostics {
    /**
     * Creates a new Diagnostics instance.
     * @param {Partial<Diagnostics>} [$$source = {}] - The source object to create the Diagnostics.
     */
    constructor($$source = {}) {
        if (!("profile_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile_id"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ValidationStatus}
             */
            this["status"] = ValidationStatus.$zero;
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {ValidationDiagnostic[]}
             */
            this["entries"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["redacted_preview"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diagnostics}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField2_0($$parsedSource["entries"]);
        }
        return new Diagnostics(/** @type {Partial<Diagnostics>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const EngineState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    EngineStateUninitialized: "UNINITIALIZED",
    EngineStateIdle: "IDLE",
    EngineStateValidating: "VALIDATING",
    EngineStateStarting: "STARTING",
    EngineStateStarted: "STARTED",
    EngineStateStopping: "STOPPING",
    EngineStateFatal: "FATAL",
};

export class Platform {
    /**
     * Creates a new Platform instance.
     * @param {Partial<Platform>} [$$source = {}] - The source object to create the Platform.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Platform instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Platform}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Platform(/** @type {Partial<Platform>} */($$parsedSource));
    }
}

export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["active_snapshot_id"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

export class ProfileSubscription {
    /**
     * Creates a new ProfileSubscription instance.
     * @param {Partial<ProfileSubscription>} [$$source = {}] - The source object to create the ProfileSubscription.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("profile_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("update_policy" in $$source)) {
            /**
             * @member
             * @type {SubscriptionUpdatePolicy}
             */
            this["update_policy"] = SubscriptionUpdatePolicy.$zero;
        }
        if (!("last_status" in $$source)) {
            /**
             * @member
             * @type {SubscriptionStatus}
             */
            this["last_status"] = SubscriptionStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_checked_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_updated_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content_sha256"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSubscription instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileSubscription}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSubscription(/** @type {Partial<ProfileSubscription>} */($$parsedSource));
    }
}

export class ProfileSummary {
    /**
     * Creates a new ProfileSummary instance.
     * @param {Partial<ProfileSummary>} [$$source = {}] - The source object to create the ProfileSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("has_draft" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_draft"] = false;
        }
        if (!("has_active_snapshot" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_active_snapshot"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["active_snapshot_id"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSummary(/** @type {Partial<ProfileSummary>} */($$parsedSource));
    }
}

export class RuntimeSummary {
    /**
     * Creates a new RuntimeSummary instance.
     * @param {Partial<RuntimeSummary>} [$$source = {}] - The source object to create the RuntimeSummary.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["inbound_types"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["outbound_types"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["protocols"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeSummary}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inbound_types" in $$parsedSource) {
            $$parsedSource["inbound_types"] = $$createField0_0($$parsedSource["inbound_types"]);
        }
        if ("outbound_types" in $$parsedSource) {
            $$parsedSource["outbound_types"] = $$createField1_0($$parsedSource["outbound_types"]);
        }
        if ("protocols" in $$parsedSource) {
            $$parsedSource["protocols"] = $$createField2_0($$parsedSource["protocols"]);
        }
        return new RuntimeSummary(/** @type {Partial<RuntimeSummary>} */($$parsedSource));
    }
}

export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("profile_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile_id"] = "";
        }
        if (!("validation_status" in $$source)) {
            /**
             * @member
             * @type {ValidationStatus}
             */
            this["validation_status"] = ValidationStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ValidationDiagnostic[] | undefined}
             */
            this["diagnostics"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RuntimeSummary | null | undefined}
             */
            this["runtime_summary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["required_capabilities"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField3_0($$parsedSource["diagnostics"]);
        }
        if ("runtime_summary" in $$parsedSource) {
            $$parsedSource["runtime_summary"] = $$createField4_0($$parsedSource["runtime_summary"]);
        }
        if ("required_capabilities" in $$parsedSource) {
            $$parsedSource["required_capabilities"] = $$createField5_0($$parsedSource["required_capabilities"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

export class SnapshotSummary {
    /**
     * Creates a new SnapshotSummary instance.
     * @param {Partial<SnapshotSummary>} [$$source = {}] - The source object to create the SnapshotSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("profile_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile_id"] = "";
        }
        if (!("validation_status" in $$source)) {
            /**
             * @member
             * @type {ValidationStatus}
             */
            this["validation_status"] = ValidationStatus.$zero;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotSummary(/** @type {Partial<SnapshotSummary>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const SubscriptionStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SubscriptionStatusPending: "pending",
    SubscriptionStatusUpdated: "updated",
    SubscriptionStatusFailed: "failed",
};

/**
 * @readonly
 * @enum {string}
 */
export const SubscriptionUpdatePolicy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SubscriptionUpdateManual: "manual",
};

export class ValidationDiagnostic {
    /**
     * Creates a new ValidationDiagnostic instance.
     * @param {Partial<ValidationDiagnostic>} [$$source = {}] - The source object to create the ValidationDiagnostic.
     */
    constructor($$source = {}) {
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {DiagnosticSeverity}
             */
            this["severity"] = DiagnosticSeverity.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["field"] = undefined;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationDiagnostic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationDiagnostic}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationDiagnostic(/** @type {Partial<ValidationDiagnostic>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ValidationStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ValidationStatusValid: "valid",
    ValidationStatusInvalid: "invalid",
    ValidationStatusUnknown: "unknown",
};

// Private type creation functions
const $$createType0 = ValidationDiagnostic.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = RuntimeSummary.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
