// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export class Capability {
    /**
     * Creates a new Capability instance.
     * @param {Partial<Capability>} [$$source = {}] - The source object to create the Capability.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {CapabilityState}
             */
            this["state"] = CapabilityState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capability instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Capability}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capability(/** @type {Partial<Capability>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const CapabilityState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CapabilityAvailable: "available",
    CapabilityUnavailable: "unavailable",
    CapabilityPartial: "partial",
    CapabilityDegraded: "degraded",
    CapabilityUnsupported: "unsupported",
};

export class EngineGetStatusReply {
    /**
     * Creates a new EngineGetStatusReply instance.
     * @param {Partial<EngineGetStatusReply>} [$$source = {}] - The source object to create the EngineGetStatusReply.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {EngineStatus}
             */
            this["status"] = (new EngineStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineGetStatusReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineGetStatusReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        return new EngineGetStatusReply(/** @type {Partial<EngineGetStatusReply>} */($$parsedSource));
    }
}

export class EngineGetStatusResult {
    /**
     * Creates a new EngineGetStatusResult instance.
     * @param {Partial<EngineGetStatusResult>} [$$source = {}] - The source object to create the EngineGetStatusResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineGetStatusReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineGetStatusResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineGetStatusResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineGetStatusResult(/** @type {Partial<EngineGetStatusResult>} */($$parsedSource));
    }
}

export class EngineStartReply {
    /**
     * Creates a new EngineStartReply instance.
     * @param {Partial<EngineStartReply>} [$$source = {}] - The source object to create the EngineStartReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStartReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStartReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineStartReply(/** @type {Partial<EngineStartReply>} */($$parsedSource));
    }
}

export class EngineStartResult {
    /**
     * Creates a new EngineStartResult instance.
     * @param {Partial<EngineStartResult>} [$$source = {}] - The source object to create the EngineStartResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineStartReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStartResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineStartResult(/** @type {Partial<EngineStartResult>} */($$parsedSource));
    }
}

export class EngineStatus {
    /**
     * Creates a new EngineStatus instance.
     * @param {Partial<EngineStatus>} [$$source = {}] - The source object to create the EngineStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {model$0.EngineState}
             */
            this["state"] = model$0.EngineState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["active_snapshot_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineStatus(/** @type {Partial<EngineStatus>} */($$parsedSource));
    }
}

export class EngineStopReply {
    /**
     * Creates a new EngineStopReply instance.
     * @param {Partial<EngineStopReply>} [$$source = {}] - The source object to create the EngineStopReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStopReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStopReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineStopReply(/** @type {Partial<EngineStopReply>} */($$parsedSource));
    }
}

export class EngineStopResult {
    /**
     * Creates a new EngineStopResult instance.
     * @param {Partial<EngineStopResult>} [$$source = {}] - The source object to create the EngineStopResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineStopReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStopResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStopResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineStopResult(/** @type {Partial<EngineStopResult>} */($$parsedSource));
    }
}

export class HelloReply {
    /**
     * Creates a new HelloReply instance.
     * @param {Partial<HelloReply>} [$$source = {}] - The source object to create the HelloReply.
     */
    constructor($$source = {}) {
        if (!("api_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_version"] = "";
        }
        if (!("min_supported_api_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["min_supported_api_version"] = "";
        }
        if (!("schema_revision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema_revision"] = "";
        }
        if (!("app_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_version"] = "";
        }
        if (!("qkboxd_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qkboxd_version"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {model$0.Platform}
             */
            this["platform"] = (new model$0.Platform());
        }
        if (!("runtime_capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["runtime_capabilities"] = [];
        }
        if (!("platform_capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["platform_capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelloReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelloReply}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("platform" in $$parsedSource) {
            $$parsedSource["platform"] = $$createField5_0($$parsedSource["platform"]);
        }
        if ("runtime_capabilities" in $$parsedSource) {
            $$parsedSource["runtime_capabilities"] = $$createField6_0($$parsedSource["runtime_capabilities"]);
        }
        if ("platform_capabilities" in $$parsedSource) {
            $$parsedSource["platform_capabilities"] = $$createField7_0($$parsedSource["platform_capabilities"]);
        }
        return new HelloReply(/** @type {Partial<HelloReply>} */($$parsedSource));
    }
}

export class HelloResult {
    /**
     * Creates a new HelloResult instance.
     * @param {Partial<HelloResult>} [$$source = {}] - The source object to create the HelloResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HelloReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelloResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelloResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new HelloResult(/** @type {Partial<HelloResult>} */($$parsedSource));
    }
}

export class StructuredError {
    /**
     * Creates a new StructuredError instance.
     * @param {Partial<StructuredError>} [$$source = {}] - The source object to create the StructuredError.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["detail"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("recoverable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recoverable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user_action"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["debug_ref"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StructuredError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StructuredError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StructuredError(/** @type {Partial<StructuredError>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = EngineStatus.createFrom;
const $$createType1 = EngineGetStatusReply.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = StructuredError.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = EngineStartReply.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = EngineStopReply.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = model$0.Platform.createFrom;
const $$createType10 = Capability.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = HelloReply.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
