// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export class Capability {
    /**
     * Creates a new Capability instance.
     * @param {Partial<Capability>} [$$source = {}] - The source object to create the Capability.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {CapabilityState}
             */
            this["state"] = CapabilityState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capability instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Capability}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capability(/** @type {Partial<Capability>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const CapabilityState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CapabilityAvailable: "available",
    CapabilityUnavailable: "unavailable",
    CapabilityPartial: "partial",
    CapabilityDegraded: "degraded",
    CapabilityUnsupported: "unsupported",
};

export class EngineCloseAllConnectionsReply {
    /**
     * Creates a new EngineCloseAllConnectionsReply instance.
     * @param {Partial<EngineCloseAllConnectionsReply>} [$$source = {}] - The source object to create the EngineCloseAllConnectionsReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineCloseAllConnectionsReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineCloseAllConnectionsReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineCloseAllConnectionsReply(/** @type {Partial<EngineCloseAllConnectionsReply>} */($$parsedSource));
    }
}

export class EngineCloseAllConnectionsResult {
    /**
     * Creates a new EngineCloseAllConnectionsResult instance.
     * @param {Partial<EngineCloseAllConnectionsResult>} [$$source = {}] - The source object to create the EngineCloseAllConnectionsResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineCloseAllConnectionsReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineCloseAllConnectionsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineCloseAllConnectionsResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineCloseAllConnectionsResult(/** @type {Partial<EngineCloseAllConnectionsResult>} */($$parsedSource));
    }
}

export class EngineCloseConnectionReply {
    /**
     * Creates a new EngineCloseConnectionReply instance.
     * @param {Partial<EngineCloseConnectionReply>} [$$source = {}] - The source object to create the EngineCloseConnectionReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineCloseConnectionReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineCloseConnectionReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineCloseConnectionReply(/** @type {Partial<EngineCloseConnectionReply>} */($$parsedSource));
    }
}

export class EngineCloseConnectionRequest {
    /**
     * Creates a new EngineCloseConnectionRequest instance.
     * @param {Partial<EngineCloseConnectionRequest>} [$$source = {}] - The source object to create the EngineCloseConnectionRequest.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineCloseConnectionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineCloseConnectionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineCloseConnectionRequest(/** @type {Partial<EngineCloseConnectionRequest>} */($$parsedSource));
    }
}

export class EngineCloseConnectionResult {
    /**
     * Creates a new EngineCloseConnectionResult instance.
     * @param {Partial<EngineCloseConnectionResult>} [$$source = {}] - The source object to create the EngineCloseConnectionResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineCloseConnectionReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineCloseConnectionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineCloseConnectionResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineCloseConnectionResult(/** @type {Partial<EngineCloseConnectionResult>} */($$parsedSource));
    }
}

export class EngineGetRuntimeCapabilitiesReply {
    /**
     * Creates a new EngineGetRuntimeCapabilitiesReply instance.
     * @param {Partial<EngineGetRuntimeCapabilitiesReply>} [$$source = {}] - The source object to create the EngineGetRuntimeCapabilitiesReply.
     */
    constructor($$source = {}) {
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineGetRuntimeCapabilitiesReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineGetRuntimeCapabilitiesReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField0_0($$parsedSource["capabilities"]);
        }
        return new EngineGetRuntimeCapabilitiesReply(/** @type {Partial<EngineGetRuntimeCapabilitiesReply>} */($$parsedSource));
    }
}

export class EngineGetRuntimeCapabilitiesResult {
    /**
     * Creates a new EngineGetRuntimeCapabilitiesResult instance.
     * @param {Partial<EngineGetRuntimeCapabilitiesResult>} [$$source = {}] - The source object to create the EngineGetRuntimeCapabilitiesResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineGetRuntimeCapabilitiesReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineGetRuntimeCapabilitiesResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineGetRuntimeCapabilitiesResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineGetRuntimeCapabilitiesResult(/** @type {Partial<EngineGetRuntimeCapabilitiesResult>} */($$parsedSource));
    }
}

export class EngineGetStatusReply {
    /**
     * Creates a new EngineGetStatusReply instance.
     * @param {Partial<EngineGetStatusReply>} [$$source = {}] - The source object to create the EngineGetStatusReply.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {EngineStatus}
             */
            this["status"] = (new EngineStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineGetStatusReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineGetStatusReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        return new EngineGetStatusReply(/** @type {Partial<EngineGetStatusReply>} */($$parsedSource));
    }
}

export class EngineGetStatusResult {
    /**
     * Creates a new EngineGetStatusResult instance.
     * @param {Partial<EngineGetStatusResult>} [$$source = {}] - The source object to create the EngineGetStatusResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineGetStatusReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineGetStatusResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineGetStatusResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineGetStatusResult(/** @type {Partial<EngineGetStatusResult>} */($$parsedSource));
    }
}

export class EngineListGroupsReply {
    /**
     * Creates a new EngineListGroupsReply instance.
     * @param {Partial<EngineListGroupsReply>} [$$source = {}] - The source object to create the EngineListGroupsReply.
     */
    constructor($$source = {}) {
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {OutboundGroup[]}
             */
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineListGroupsReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineListGroupsReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        return new EngineListGroupsReply(/** @type {Partial<EngineListGroupsReply>} */($$parsedSource));
    }
}

export class EngineListGroupsResult {
    /**
     * Creates a new EngineListGroupsResult instance.
     * @param {Partial<EngineListGroupsResult>} [$$source = {}] - The source object to create the EngineListGroupsResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineListGroupsReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineListGroupsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineListGroupsResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineListGroupsResult(/** @type {Partial<EngineListGroupsResult>} */($$parsedSource));
    }
}

export class EngineReloadReply {
    /**
     * Creates a new EngineReloadReply instance.
     * @param {Partial<EngineReloadReply>} [$$source = {}] - The source object to create the EngineReloadReply.
     */
    constructor($$source = {}) {
        if (!("outcome" in $$source)) {
            /**
             * @member
             * @type {ReloadOutcome}
             */
            this["outcome"] = ReloadOutcome.$zero;
        }
        if (!("target_snapshot_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_snapshot_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["previous_snapshot_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["active_snapshot_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["failure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["cleanup_failure"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineReloadReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineReloadReply}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failure" in $$parsedSource) {
            $$parsedSource["failure"] = $$createField4_0($$parsedSource["failure"]);
        }
        if ("cleanup_failure" in $$parsedSource) {
            $$parsedSource["cleanup_failure"] = $$createField5_0($$parsedSource["cleanup_failure"]);
        }
        return new EngineReloadReply(/** @type {Partial<EngineReloadReply>} */($$parsedSource));
    }
}

export class EngineReloadRequest {
    /**
     * Creates a new EngineReloadRequest instance.
     * @param {Partial<EngineReloadRequest>} [$$source = {}] - The source object to create the EngineReloadRequest.
     */
    constructor($$source = {}) {
        if (!("snapshot_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snapshot_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineReloadRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineReloadRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineReloadRequest(/** @type {Partial<EngineReloadRequest>} */($$parsedSource));
    }
}

export class EngineReloadResult {
    /**
     * Creates a new EngineReloadResult instance.
     * @param {Partial<EngineReloadResult>} [$$source = {}] - The source object to create the EngineReloadResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineReloadReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineReloadResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineReloadResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType18;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineReloadResult(/** @type {Partial<EngineReloadResult>} */($$parsedSource));
    }
}

export class EngineSelectOutboundReply {
    /**
     * Creates a new EngineSelectOutboundReply instance.
     * @param {Partial<EngineSelectOutboundReply>} [$$source = {}] - The source object to create the EngineSelectOutboundReply.
     */
    constructor($$source = {}) {
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {OutboundGroup}
             */
            this["group"] = (new OutboundGroup());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineSelectOutboundReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineSelectOutboundReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("group" in $$parsedSource) {
            $$parsedSource["group"] = $$createField0_0($$parsedSource["group"]);
        }
        return new EngineSelectOutboundReply(/** @type {Partial<EngineSelectOutboundReply>} */($$parsedSource));
    }
}

export class EngineSelectOutboundRequest {
    /**
     * Creates a new EngineSelectOutboundRequest instance.
     * @param {Partial<EngineSelectOutboundRequest>} [$$source = {}] - The source object to create the EngineSelectOutboundRequest.
     */
    constructor($$source = {}) {
        if (!("group_tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_tag"] = "";
        }
        if (!("outbound_tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outbound_tag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineSelectOutboundRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineSelectOutboundRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineSelectOutboundRequest(/** @type {Partial<EngineSelectOutboundRequest>} */($$parsedSource));
    }
}

export class EngineSelectOutboundResult {
    /**
     * Creates a new EngineSelectOutboundResult instance.
     * @param {Partial<EngineSelectOutboundResult>} [$$source = {}] - The source object to create the EngineSelectOutboundResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineSelectOutboundReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineSelectOutboundResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineSelectOutboundResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType20;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineSelectOutboundResult(/** @type {Partial<EngineSelectOutboundResult>} */($$parsedSource));
    }
}

export class EngineStartReply {
    /**
     * Creates a new EngineStartReply instance.
     * @param {Partial<EngineStartReply>} [$$source = {}] - The source object to create the EngineStartReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStartReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStartReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineStartReply(/** @type {Partial<EngineStartReply>} */($$parsedSource));
    }
}

export class EngineStartResult {
    /**
     * Creates a new EngineStartResult instance.
     * @param {Partial<EngineStartResult>} [$$source = {}] - The source object to create the EngineStartResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineStartReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStartResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineStartResult(/** @type {Partial<EngineStartResult>} */($$parsedSource));
    }
}

export class EngineStatus {
    /**
     * Creates a new EngineStatus instance.
     * @param {Partial<EngineStatus>} [$$source = {}] - The source object to create the EngineStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {model$0.EngineState}
             */
            this["state"] = model$0.EngineState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["active_snapshot_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error_message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineStatus(/** @type {Partial<EngineStatus>} */($$parsedSource));
    }
}

export class EngineStopReply {
    /**
     * Creates a new EngineStopReply instance.
     * @param {Partial<EngineStopReply>} [$$source = {}] - The source object to create the EngineStopReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStopReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStopReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineStopReply(/** @type {Partial<EngineStopReply>} */($$parsedSource));
    }
}

export class EngineStopResult {
    /**
     * Creates a new EngineStopResult instance.
     * @param {Partial<EngineStopResult>} [$$source = {}] - The source object to create the EngineStopResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineStopReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineStopResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineStopResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineStopResult(/** @type {Partial<EngineStopResult>} */($$parsedSource));
    }
}

export class EngineURLTestReply {
    /**
     * Creates a new EngineURLTestReply instance.
     * @param {Partial<EngineURLTestReply>} [$$source = {}] - The source object to create the EngineURLTestReply.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {URLTestResult[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineURLTestReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineURLTestReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new EngineURLTestReply(/** @type {Partial<EngineURLTestReply>} */($$parsedSource));
    }
}

export class EngineURLTestRequest {
    /**
     * Creates a new EngineURLTestRequest instance.
     * @param {Partial<EngineURLTestRequest>} [$$source = {}] - The source object to create the EngineURLTestRequest.
     */
    constructor($$source = {}) {
        if (!("group_tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_tag"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["timeout_ms"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineURLTestRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineURLTestRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineURLTestRequest(/** @type {Partial<EngineURLTestRequest>} */($$parsedSource));
    }
}

export class EngineURLTestResult {
    /**
     * Creates a new EngineURLTestResult instance.
     * @param {Partial<EngineURLTestResult>} [$$source = {}] - The source object to create the EngineURLTestResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {EngineURLTestReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineURLTestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineURLTestResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType28;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new EngineURLTestResult(/** @type {Partial<EngineURLTestResult>} */($$parsedSource));
    }
}

export class GetPlatformCapabilitiesReply {
    /**
     * Creates a new GetPlatformCapabilitiesReply instance.
     * @param {Partial<GetPlatformCapabilitiesReply>} [$$source = {}] - The source object to create the GetPlatformCapabilitiesReply.
     */
    constructor($$source = {}) {
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetPlatformCapabilitiesReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetPlatformCapabilitiesReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField0_0($$parsedSource["capabilities"]);
        }
        return new GetPlatformCapabilitiesReply(/** @type {Partial<GetPlatformCapabilitiesReply>} */($$parsedSource));
    }
}

export class GetPlatformCapabilitiesResult {
    /**
     * Creates a new GetPlatformCapabilitiesResult instance.
     * @param {Partial<GetPlatformCapabilitiesResult>} [$$source = {}] - The source object to create the GetPlatformCapabilitiesResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GetPlatformCapabilitiesReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetPlatformCapabilitiesResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetPlatformCapabilitiesResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType30;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new GetPlatformCapabilitiesResult(/** @type {Partial<GetPlatformCapabilitiesResult>} */($$parsedSource));
    }
}

export class GetPrivilegedProviderStatusReply {
    /**
     * Creates a new GetPrivilegedProviderStatusReply instance.
     * @param {Partial<GetPrivilegedProviderStatusReply>} [$$source = {}] - The source object to create the GetPrivilegedProviderStatusReply.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {PrivilegedProviderStatus}
             */
            this["status"] = (new PrivilegedProviderStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetPrivilegedProviderStatusReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetPrivilegedProviderStatusReply}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        return new GetPrivilegedProviderStatusReply(/** @type {Partial<GetPrivilegedProviderStatusReply>} */($$parsedSource));
    }
}

export class GetPrivilegedProviderStatusResult {
    /**
     * Creates a new GetPrivilegedProviderStatusResult instance.
     * @param {Partial<GetPrivilegedProviderStatusResult>} [$$source = {}] - The source object to create the GetPrivilegedProviderStatusResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GetPrivilegedProviderStatusReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetPrivilegedProviderStatusResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetPrivilegedProviderStatusResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType33;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new GetPrivilegedProviderStatusResult(/** @type {Partial<GetPrivilegedProviderStatusResult>} */($$parsedSource));
    }
}

export class GetSystemProxyStatusReply {
    /**
     * Creates a new GetSystemProxyStatusReply instance.
     * @param {Partial<GetSystemProxyStatusReply>} [$$source = {}] - The source object to create the GetSystemProxyStatusReply.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (!("os_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["os_enabled"] = false;
        }
        if (!("qkbox_owned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["qkbox_owned"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetSystemProxyStatusReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetSystemProxyStatusReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetSystemProxyStatusReply(/** @type {Partial<GetSystemProxyStatusReply>} */($$parsedSource));
    }
}

export class GetSystemProxyStatusResult {
    /**
     * Creates a new GetSystemProxyStatusResult instance.
     * @param {Partial<GetSystemProxyStatusResult>} [$$source = {}] - The source object to create the GetSystemProxyStatusResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GetSystemProxyStatusReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetSystemProxyStatusResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetSystemProxyStatusResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType35;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new GetSystemProxyStatusResult(/** @type {Partial<GetSystemProxyStatusResult>} */($$parsedSource));
    }
}

export class HelloReply {
    /**
     * Creates a new HelloReply instance.
     * @param {Partial<HelloReply>} [$$source = {}] - The source object to create the HelloReply.
     */
    constructor($$source = {}) {
        if (!("api_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_version"] = "";
        }
        if (!("min_supported_api_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["min_supported_api_version"] = "";
        }
        if (!("schema_revision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema_revision"] = "";
        }
        if (!("app_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_version"] = "";
        }
        if (!("qkboxd_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qkboxd_version"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {model$0.Platform}
             */
            this["platform"] = (new model$0.Platform());
        }
        if (!("runtime_capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["runtime_capabilities"] = [];
        }
        if (!("platform_capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["platform_capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelloReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelloReply}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType36;
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("platform" in $$parsedSource) {
            $$parsedSource["platform"] = $$createField5_0($$parsedSource["platform"]);
        }
        if ("runtime_capabilities" in $$parsedSource) {
            $$parsedSource["runtime_capabilities"] = $$createField6_0($$parsedSource["runtime_capabilities"]);
        }
        if ("platform_capabilities" in $$parsedSource) {
            $$parsedSource["platform_capabilities"] = $$createField7_0($$parsedSource["platform_capabilities"]);
        }
        return new HelloReply(/** @type {Partial<HelloReply>} */($$parsedSource));
    }
}

export class HelloResult {
    /**
     * Creates a new HelloResult instance.
     * @param {Partial<HelloResult>} [$$source = {}] - The source object to create the HelloResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HelloReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelloResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelloResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType38;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new HelloResult(/** @type {Partial<HelloResult>} */($$parsedSource));
    }
}

export class OutboundGroup {
    /**
     * Creates a new OutboundGroup instance.
     * @param {Partial<OutboundGroup>} [$$source = {}] - The source object to create the OutboundGroup.
     */
    constructor($$source = {}) {
        if (!("tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("selected" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selected"] = "";
        }
        if (!("outbounds" in $$source)) {
            /**
             * @member
             * @type {OutboundOption[]}
             */
            this["outbounds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutboundGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OutboundGroup}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType40;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outbounds" in $$parsedSource) {
            $$parsedSource["outbounds"] = $$createField3_0($$parsedSource["outbounds"]);
        }
        return new OutboundGroup(/** @type {Partial<OutboundGroup>} */($$parsedSource));
    }
}

export class OutboundOption {
    /**
     * Creates a new OutboundOption instance.
     * @param {Partial<OutboundOption>} [$$source = {}] - The source object to create the OutboundOption.
     */
    constructor($$source = {}) {
        if (!("tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["delay_ms"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutboundOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OutboundOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutboundOption(/** @type {Partial<OutboundOption>} */($$parsedSource));
    }
}

export class PrepareFeatureReply {
    /**
     * Creates a new PrepareFeatureReply instance.
     * @param {Partial<PrepareFeatureReply>} [$$source = {}] - The source object to create the PrepareFeatureReply.
     */
    constructor($$source = {}) {
        if (!("feature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feature"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {CapabilityState}
             */
            this["state"] = CapabilityState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrepareFeatureReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrepareFeatureReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrepareFeatureReply(/** @type {Partial<PrepareFeatureReply>} */($$parsedSource));
    }
}

export class PrepareFeatureRequest {
    /**
     * Creates a new PrepareFeatureRequest instance.
     * @param {Partial<PrepareFeatureRequest>} [$$source = {}] - The source object to create the PrepareFeatureRequest.
     */
    constructor($$source = {}) {
        if (!("feature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feature"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrepareFeatureRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrepareFeatureRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrepareFeatureRequest(/** @type {Partial<PrepareFeatureRequest>} */($$parsedSource));
    }
}

export class PrepareFeatureResult {
    /**
     * Creates a new PrepareFeatureResult instance.
     * @param {Partial<PrepareFeatureResult>} [$$source = {}] - The source object to create the PrepareFeatureResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PrepareFeatureReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrepareFeatureResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrepareFeatureResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType42;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new PrepareFeatureResult(/** @type {Partial<PrepareFeatureResult>} */($$parsedSource));
    }
}

export class PrivilegedProviderStatus {
    /**
     * Creates a new PrivilegedProviderStatus instance.
     * @param {Partial<PrivilegedProviderStatus>} [$$source = {}] - The source object to create the PrivilegedProviderStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("reachable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reachable"] = false;
        }
        if (!("authenticated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["authenticated"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["expected_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ProviderOwnerState | null | undefined}
             */
            this["owner_state"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrivilegedProviderStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrivilegedProviderStatus}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("owner_state" in $$parsedSource) {
            $$parsedSource["owner_state"] = $$createField6_0($$parsedSource["owner_state"]);
        }
        return new PrivilegedProviderStatus(/** @type {Partial<PrivilegedProviderStatus>} */($$parsedSource));
    }
}

export class ProviderOwnerState {
    /**
     * Creates a new ProviderOwnerState instance.
     * @param {Partial<ProviderOwnerState>} [$$source = {}] - The source object to create the ProviderOwnerState.
     */
    constructor($$source = {}) {
        if (!("owned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["owned"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["uid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["session_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["runtime_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["started_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderOwnerState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderOwnerState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderOwnerState(/** @type {Partial<ProviderOwnerState>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ReloadOutcome = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ReloadOutcomeSuccess: "success",
    ReloadOutcomeFailedValidation: "failed_validation",
    ReloadOutcomeFailedPermission: "failed_permission",
    ReloadOutcomeFailedPlatformPrepare: "failed_platform_prepare",
    ReloadOutcomeFailedRuntimeStart: "failed_runtime_start",
    ReloadOutcomeRolledBack: "rolled_back",
    ReloadOutcomeDegraded: "degraded",
    ReloadOutcomeCleanupFailed: "cleanup_failed",
};

export class RunRepairActionReply {
    /**
     * Creates a new RunRepairActionReply instance.
     * @param {Partial<RunRepairActionReply>} [$$source = {}] - The source object to create the RunRepairActionReply.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("outcome" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outcome"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunRepairActionReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunRepairActionReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunRepairActionReply(/** @type {Partial<RunRepairActionReply>} */($$parsedSource));
    }
}

export class RunRepairActionRequest {
    /**
     * Creates a new RunRepairActionRequest instance.
     * @param {Partial<RunRepairActionRequest>} [$$source = {}] - The source object to create the RunRepairActionRequest.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunRepairActionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunRepairActionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunRepairActionRequest(/** @type {Partial<RunRepairActionRequest>} */($$parsedSource));
    }
}

export class RunRepairActionResult {
    /**
     * Creates a new RunRepairActionResult instance.
     * @param {Partial<RunRepairActionResult>} [$$source = {}] - The source object to create the RunRepairActionResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RunRepairActionReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunRepairActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunRepairActionResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType46;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new RunRepairActionResult(/** @type {Partial<RunRepairActionResult>} */($$parsedSource));
    }
}

export class RuntimeEventBridgeStartReply {
    /**
     * Creates a new RuntimeEventBridgeStartReply instance.
     * @param {Partial<RuntimeEventBridgeStartReply>} [$$source = {}] - The source object to create the RuntimeEventBridgeStartReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeEventBridgeStartReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeEventBridgeStartReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeEventBridgeStartReply(/** @type {Partial<RuntimeEventBridgeStartReply>} */($$parsedSource));
    }
}

export class RuntimeEventBridgeStartResult {
    /**
     * Creates a new RuntimeEventBridgeStartResult instance.
     * @param {Partial<RuntimeEventBridgeStartResult>} [$$source = {}] - The source object to create the RuntimeEventBridgeStartResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RuntimeEventBridgeStartReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeEventBridgeStartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeEventBridgeStartResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType48;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new RuntimeEventBridgeStartResult(/** @type {Partial<RuntimeEventBridgeStartResult>} */($$parsedSource));
    }
}

export class RuntimeEventBridgeStopReply {
    /**
     * Creates a new RuntimeEventBridgeStopReply instance.
     * @param {Partial<RuntimeEventBridgeStopReply>} [$$source = {}] - The source object to create the RuntimeEventBridgeStopReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeEventBridgeStopReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeEventBridgeStopReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeEventBridgeStopReply(/** @type {Partial<RuntimeEventBridgeStopReply>} */($$parsedSource));
    }
}

export class RuntimeEventBridgeStopResult {
    /**
     * Creates a new RuntimeEventBridgeStopResult instance.
     * @param {Partial<RuntimeEventBridgeStopResult>} [$$source = {}] - The source object to create the RuntimeEventBridgeStopResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RuntimeEventBridgeStopReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeEventBridgeStopResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeEventBridgeStopResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType50;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new RuntimeEventBridgeStopResult(/** @type {Partial<RuntimeEventBridgeStopResult>} */($$parsedSource));
    }
}

export class SetSystemProxyEnabledReply {
    /**
     * Creates a new SetSystemProxyEnabledReply instance.
     * @param {Partial<SetSystemProxyEnabledReply>} [$$source = {}] - The source object to create the SetSystemProxyEnabledReply.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetSystemProxyEnabledReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetSystemProxyEnabledReply}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetSystemProxyEnabledReply(/** @type {Partial<SetSystemProxyEnabledReply>} */($$parsedSource));
    }
}

export class SetSystemProxyEnabledRequest {
    /**
     * Creates a new SetSystemProxyEnabledRequest instance.
     * @param {Partial<SetSystemProxyEnabledRequest>} [$$source = {}] - The source object to create the SetSystemProxyEnabledRequest.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetSystemProxyEnabledRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetSystemProxyEnabledRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetSystemProxyEnabledRequest(/** @type {Partial<SetSystemProxyEnabledRequest>} */($$parsedSource));
    }
}

export class SetSystemProxyEnabledResult {
    /**
     * Creates a new SetSystemProxyEnabledResult instance.
     * @param {Partial<SetSystemProxyEnabledResult>} [$$source = {}] - The source object to create the SetSystemProxyEnabledResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SetSystemProxyEnabledReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetSystemProxyEnabledResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetSystemProxyEnabledResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType52;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new SetSystemProxyEnabledResult(/** @type {Partial<SetSystemProxyEnabledResult>} */($$parsedSource));
    }
}

export class StructuredError {
    /**
     * Creates a new StructuredError instance.
     * @param {Partial<StructuredError>} [$$source = {}] - The source object to create the StructuredError.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["detail"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("recoverable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recoverable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user_action"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["debug_ref"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StructuredError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StructuredError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StructuredError(/** @type {Partial<StructuredError>} */($$parsedSource));
    }
}

export class URLTestResult {
    /**
     * Creates a new URLTestResult instance.
     * @param {Partial<URLTestResult>} [$$source = {}] - The source object to create the URLTestResult.
     */
    constructor($$source = {}) {
        if (!("outbound" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outbound"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["delay_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new URLTestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {URLTestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new URLTestResult(/** @type {Partial<URLTestResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = EngineCloseAllConnectionsReply.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = StructuredError.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = EngineCloseConnectionReply.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = Capability.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = EngineGetRuntimeCapabilitiesReply.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = EngineStatus.createFrom;
const $$createType11 = EngineGetStatusReply.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = OutboundGroup.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = EngineListGroupsReply.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = EngineReloadReply.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = EngineSelectOutboundReply.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = EngineStartReply.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = EngineStopReply.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = URLTestResult.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = EngineURLTestReply.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = GetPlatformCapabilitiesReply.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = PrivilegedProviderStatus.createFrom;
const $$createType32 = GetPrivilegedProviderStatusReply.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = GetSystemProxyStatusReply.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = model$0.Platform.createFrom;
const $$createType37 = HelloReply.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = OutboundOption.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = PrepareFeatureReply.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = ProviderOwnerState.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = RunRepairActionReply.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = RuntimeEventBridgeStartReply.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = RuntimeEventBridgeStopReply.createFrom;
const $$createType50 = $Create.Nullable($$createType49);
const $$createType51 = SetSystemProxyEnabledReply.createFrom;
const $$createType52 = $Create.Nullable($$createType51);
