// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export class Capability {
    /**
     * Creates a new Capability instance.
     * @param {Partial<Capability>} [$$source = {}] - The source object to create the Capability.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {CapabilityState}
             */
            this["state"] = CapabilityState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capability instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Capability}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capability(/** @type {Partial<Capability>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const CapabilityState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CapabilityAvailable: "available",
    CapabilityUnavailable: "unavailable",
    CapabilityPartial: "partial",
    CapabilityDegraded: "degraded",
    CapabilityUnsupported: "unsupported",
};

export class HelloReply {
    /**
     * Creates a new HelloReply instance.
     * @param {Partial<HelloReply>} [$$source = {}] - The source object to create the HelloReply.
     */
    constructor($$source = {}) {
        if (!("api_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_version"] = "";
        }
        if (!("min_supported_api_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["min_supported_api_version"] = "";
        }
        if (!("schema_revision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema_revision"] = "";
        }
        if (!("app_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_version"] = "";
        }
        if (!("qkboxd_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qkboxd_version"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {model$0.Platform}
             */
            this["platform"] = (new model$0.Platform());
        }
        if (!("runtime_capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["runtime_capabilities"] = [];
        }
        if (!("platform_capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["platform_capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelloReply instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelloReply}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("platform" in $$parsedSource) {
            $$parsedSource["platform"] = $$createField5_0($$parsedSource["platform"]);
        }
        if ("runtime_capabilities" in $$parsedSource) {
            $$parsedSource["runtime_capabilities"] = $$createField6_0($$parsedSource["runtime_capabilities"]);
        }
        if ("platform_capabilities" in $$parsedSource) {
            $$parsedSource["platform_capabilities"] = $$createField7_0($$parsedSource["platform_capabilities"]);
        }
        return new HelloReply(/** @type {Partial<HelloReply>} */($$parsedSource));
    }
}

export class HelloResult {
    /**
     * Creates a new HelloResult instance.
     * @param {Partial<HelloResult>} [$$source = {}] - The source object to create the HelloResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HelloReply | null | undefined}
             */
            this["reply"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StructuredError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelloResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelloResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply" in $$parsedSource) {
            $$parsedSource["reply"] = $$createField0_0($$parsedSource["reply"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new HelloResult(/** @type {Partial<HelloResult>} */($$parsedSource));
    }
}

export class StructuredError {
    /**
     * Creates a new StructuredError instance.
     * @param {Partial<StructuredError>} [$$source = {}] - The source object to create the StructuredError.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["detail"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("recoverable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recoverable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user_action"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["debug_ref"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StructuredError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StructuredError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StructuredError(/** @type {Partial<StructuredError>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = model$0.Platform.createFrom;
const $$createType1 = Capability.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = HelloReply.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = StructuredError.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
