// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../shared/api/models.js";

/**
 * @returns {$CancellablePromise<api$0.EngineCloseAllConnectionsResult>}
 */
export function EngineCloseAllConnections() {
    return $Call.ByID(3927402430).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {api$0.EngineCloseConnectionRequest} req
 * @returns {$CancellablePromise<api$0.EngineCloseConnectionResult>}
 */
export function EngineCloseConnection(req) {
    return $Call.ByID(4199505442, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.EngineGetRuntimeCapabilitiesResult>}
 */
export function EngineGetRuntimeCapabilities() {
    return $Call.ByID(2142958192).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.EngineGetStatusResult>}
 */
export function EngineGetStatus() {
    return $Call.ByID(4219929464).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.EngineListGroupsResult>}
 */
export function EngineListGroups() {
    return $Call.ByID(2435842894).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {api$0.EngineReloadRequest} req
 * @returns {$CancellablePromise<api$0.EngineReloadResult>}
 */
export function EngineReload(req) {
    return $Call.ByID(3490906975, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {api$0.EngineSelectOutboundRequest} req
 * @returns {$CancellablePromise<api$0.EngineSelectOutboundResult>}
 */
export function EngineSelectOutbound(req) {
    return $Call.ByID(1847711966, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.EngineStartResult>}
 */
export function EngineStart() {
    return $Call.ByID(3171975010).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.EngineStopResult>}
 */
export function EngineStop() {
    return $Call.ByID(3329435234).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {api$0.EngineURLTestRequest} req
 * @returns {$CancellablePromise<api$0.EngineURLTestResult>}
 */
export function EngineURLTest(req) {
    return $Call.ByID(3295221719, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.HelloResult>}
 */
export function Hello() {
    return $Call.ByID(1026108960).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.GetPlatformCapabilitiesResult>}
 */
export function PlatformGetCapabilities() {
    return $Call.ByID(521480311).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.GetPrivilegedProviderStatusResult>}
 */
export function PlatformGetPrivilegedProviderStatus() {
    return $Call.ByID(1026306247).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.GetSystemProxyStatusResult>}
 */
export function PlatformGetSystemProxyStatus() {
    return $Call.ByID(538798670).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {api$0.PrepareFeatureRequest} req
 * @returns {$CancellablePromise<api$0.PrepareFeatureResult>}
 */
export function PlatformPrepareFeature(req) {
    return $Call.ByID(1517982888, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {api$0.RunRepairActionRequest} req
 * @returns {$CancellablePromise<api$0.RunRepairActionResult>}
 */
export function PlatformRunRepairAction(req) {
    return $Call.ByID(4193203891, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {api$0.SetSystemProxyEnabledRequest} req
 * @returns {$CancellablePromise<api$0.SetSystemProxyEnabledResult>}
 */
export function PlatformSetSystemProxyEnabled(req) {
    return $Call.ByID(1610130657, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.RuntimeEventBridgeStartResult>}
 */
export function StartRuntimeEventBridge() {
    return $Call.ByID(2560008773).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.RuntimeEventBridgeStopResult>}
 */
export function StopRuntimeEventBridge() {
    return $Call.ByID(3118977417).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

// Private type creation functions
const $$createType0 = api$0.EngineCloseAllConnectionsResult.createFrom;
const $$createType1 = api$0.EngineCloseConnectionResult.createFrom;
const $$createType2 = api$0.EngineGetRuntimeCapabilitiesResult.createFrom;
const $$createType3 = api$0.EngineGetStatusResult.createFrom;
const $$createType4 = api$0.EngineListGroupsResult.createFrom;
const $$createType5 = api$0.EngineReloadResult.createFrom;
const $$createType6 = api$0.EngineSelectOutboundResult.createFrom;
const $$createType7 = api$0.EngineStartResult.createFrom;
const $$createType8 = api$0.EngineStopResult.createFrom;
const $$createType9 = api$0.EngineURLTestResult.createFrom;
const $$createType10 = api$0.HelloResult.createFrom;
const $$createType11 = api$0.GetPlatformCapabilitiesResult.createFrom;
const $$createType12 = api$0.GetPrivilegedProviderStatusResult.createFrom;
const $$createType13 = api$0.GetSystemProxyStatusResult.createFrom;
const $$createType14 = api$0.PrepareFeatureResult.createFrom;
const $$createType15 = api$0.RunRepairActionResult.createFrom;
const $$createType16 = api$0.SetSystemProxyEnabledResult.createFrom;
const $$createType17 = api$0.RuntimeEventBridgeStartResult.createFrom;
const $$createType18 = api$0.RuntimeEventBridgeStopResult.createFrom;
